---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---
```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(move)
library(momentuHMM)
library(leaflet)
library(RColorBrewer)
library(sf)
library(furrr)
library(here)
library(crawl)
```

Load data for use in the assessment
```{r}
load(file=here("classifier_fall", "fall_all_data.RData"))
```

Determine which individuals *didn't* die too early (here defined as 12/15)
```{r}
id_list <- unique(amwo_hmm$ID)
id_list <- id_list[!(id_list %in% individuals_died_too_early)]
```

And now for the accuracy assessment

First: iterate through dates. Gonna start with a single date for now (11/1) and add an iterative framework on top of this. Note that this will likely be the level at which I implement parallel processing.
```{r}
jul_day_cutoff <- yday(mdy("11/1/2020") - days_subtract)

#now iterating through individuals
id_iter <- id_list[1]

amwo_hmm_clipped <- amwo_hmm %>% #remove locations for the ID in question after the cutoff date
  filter(!(ID == id_iter & julian_day > jul_day_cutoff))
  
#load the model object and substitute amwo_hmm_clipped for m1$data

#run viterbi

#retrieve the modified ending state

#read in amwo_hmm_final and retrieve the real ending state

#report the cutoff date, ID, modified ending state, and real ending state in a tibble, which will be the output of the loop

```

