---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(tidyterra)
library(ggspatial)
library(lubridate)
library(ggpubr)
library(ggborderline)
```

Load GPS locations
```{r}
amwo_data_reconstructed <- readRDS(file = here::here("classifier_integrated", "fac_primary_state_delineation.rds")) %>% 
  arrange(animal_name, time)
#make a column that has the prior steps for each location
amwo_data_reconstructed <- amwo_data_reconstructed %>% 
  group_by(animal_name) %>% 
  group_modify(.f = function(x, y){
    if(nrow(x) == 1){
      x$prior_step <- NA
    } else {
      x$prior_step <- c(NA, x$primary_step_state[1:(nrow(x)-1)])
    }
    return(x)
  }) %>% 
  ungroup()
```

Load a basemap
```{r}
basemap_ras <- rast(there::here_file("Data", "basemaps", "esri_lightgrey", "esri_lightgrey_36_48_4326.tif")) %>% 
  project("EPSG:5070")
```

Load range map and merge fall and spring migratory ranges
```{r}
range_shp <- st_read(here::here("auxiliary_state_plot", "ebird", "amwo_combined_2021_4326.shp")) %>%
  mutate(season = recode(season, 
                         "Spring Migratory Range" = "Migratory Range",
                         "Fall Migratory Range" = "Migratory Range",
                         "Nonbreeding Range" = "Wintering Range")) %>%
  group_by(season) %>%
  summarise(geometry = sf::st_union(geometry)) %>%
  ungroup() %>% 
  filter(season != "Migratory Range") %>% #remove the migratory range from the figure
  st_transform(5070)
```

Creating template for the auxiliary state maps
```{r}
template_map <- ggplot(range_shp) +
  theme_void() +
  geom_spatraster_rgb(data = basemap_ras, maxcell = 5e+07) + #5e+05
  geom_sf(aes(fill = season), alpha = 0.5) +
  scale_fill_manual(values = c("#A65141FF", "#80A0C7FF", "#394165FF")) +
  coord_sf(xlim = c(-408613, 2763993), ylim = c(226720.6, 3589842), expand = FALSE) +
  #coord_sf(xlim = c(-100, -60), ylim = c(25, 55), expand = FALSE) +
  labs(fill = NULL) +
  annotation_north_arrow(location = "br",
                         which_north = "true",
                         height = unit(1.5/3, "cm"),
                         width = unit(1.5/3, "cm"),
                         pad_x = unit(0.3, "cm"), 
                         pad_y = unit(0.3, "cm"), 
                         style = ggspatial::north_arrow_orienteering(
                           fill = c("grey40", "white"),
                           line_col = "grey20",
                           text_size = 6
                         )) +
  annotation_scale(location = "bl", width_hint = 0.2, bar_cols = c("grey40", "white"),
                   pad_x = unit(0.3, "cm"), 
                   pad_y = unit(0.3, "cm"),) 
```

Dispersal event plots
```{r}
# Data summaries
dispersal_movements <- amwo_data_reconstructed %>% 
  filter(primary_step_state == "Dispersal" | prior_step == "Dispersal") %>% 
  mutate(date_standardized = ymd(paste0("2020-", month(time), "-", day(time)))) %>% 
  mutate(animal_name = if_else(animal_name == "RI-2019-29", if_else(year(time) == 2019, "RI-2019-29-2019", "RI-2019-29-2020"), animal_name)) #bug fix: RI-2019-29 has two dispersal events

dispersal_summary <- dispersal_movements %>% 
  group_by(animal_name) %>% 
  summarise(min_date = min(date_standardized), max_date = max(date_standardized)) %>% 
  pivot_longer(cols = c(min_date, max_date), 
               names_to = "summary_type")

dispersal_sorted <- dispersal_summary %>% 
  filter(summary_type == "min_date") %>% 
  arrange(desc(value)) %>% 
  pull(animal_name)

dispersal_summary <- dispersal_summary %>% 
  mutate(animal_name = factor(animal_name, levels = dispersal_sorted))

dispersal_sf <- dispersal_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>% 
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise()

dispersal_line <- dispersal_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>% 
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise() %>% 
  st_cast("LINESTRING")

# Revised map
dispersal_map <- template_map +
  geom_sf(data = dispersal_line, linewidth = 0.5, colour = c("#F0A0FF", "#4C005C", "#0075DC")) +
  geom_sf(data = dispersal_sf, size = 1, color = "black") +
  geom_sf(data = dispersal_sf, size = 0.8, color = c("#F0A0FF", "#4C005C", "#0075DC")) +
  coord_sf(xlim = c(1637348, 2215039), ylim = c(2192378, 2770069), expand = FALSE) +
  theme(legend.position = "bottom",
        legend.margin=margin(t = 10),
        plot.margin = margin(b = 10)) +
  ggtitle("Dispersal")

# Revised timeline
dispersal_timeline <- ggplot(data = dispersal_summary, mapping = aes(x = value, y = animal_name, group = animal_name, color = animal_name)) +
  theme_bw() +
  geom_borderline(linewidth = 0.8,
                  bordercolour = "black",
                  borderwidth = 0.3,
                  lineend = "round") +
  scale_x_date(limits = c(ymd("2020-01-01"), ymd("2020-12-31")),
               breaks = c(ymd("2020-01-01"),ymd("2020-02-01"),ymd("2020-03-01"),ymd("2020-04-01"),ymd("2020-05-01"),ymd("2020-06-01"),ymd("2020-07-01"),ymd("2020-08-01"),ymd("2020-09-01"), ymd("2020-10-01"), ymd("2020-11-01"), ymd("2020-12-01"), ymd("2021-1-01")),
               labels = c('J','F','M','A','M','J','J','A','S','O','N','D', 'J')) +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "none") +
  scale_color_manual(values = c("#F0A0FF", "#4C005C", "#0075DC")) +
  ggtitle("Dispersal")

# Combining them together
# blank <- ggplot() + theme_void()
```

Foray loop plots
```{r}
# Data summaries
foray_movements <- amwo_data_reconstructed %>% 
  filter(primary_step_state == "Foray loop" | prior_step == "Foray loop") %>% 
  mutate(date_standardized = ymd(paste0("2020-", month(time), "-", day(time))))

foray_summary <- foray_movements %>% 
  group_by(animal_name) %>% 
  summarise(min_date = min(date_standardized), max_date = max(date_standardized)) %>% 
  pivot_longer(cols = c(min_date, max_date), 
               names_to = "summary_type")

foray_sorted <- foray_summary %>% 
  filter(summary_type == "min_date") %>% 
  arrange(desc(value)) %>% 
  pull(animal_name)

foray_summary <- foray_summary %>% 
  mutate(animal_name = factor(animal_name, levels = foray_sorted))

foray_sf <- foray_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise()

foray_line <- foray_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise() %>% 
  st_cast("LINESTRING")

# Revised map
foray_map <- template_map +
  geom_sf(data = foray_line, linewidth = 0.5, colour = c("#F0A0FF", "#0075DC", "#993F00","#4A6990FF", "#4C005C", "#C20088", "#005C31", "#2BCE48", "#FFCC99", "#808080","#94FFB5", "#8F7C00", "#9DCC00")) + 
  geom_sf(data = foray_sf, size = 1, color = "black") +
  geom_sf(data = foray_sf, size = 0.8, color = c("#F0A0FF", "#0075DC", "#993F00","#4A6990FF", "#4C005C", "#C20088", "#005C31", "#2BCE48", "#FFCC99", "#808080","#94FFB5", "#8F7C00", "#9DCC00")) +
  #coord_sf(xlim = c(-100, -60), ylim = c(25, 55), expand = FALSE) +
  coord_sf(xlim = c(-408613, 2763993), ylim = c(226720.6, 3589842), expand = FALSE) +
  theme(legend.position = "bottom",
        legend.margin = margin(t = 10),
        plot.margin = margin(b = 10)) +
  ggtitle("Foray loop")

# Revised timeline
foray_timeline <- ggplot(data = foray_summary, mapping = aes(x = value, y = animal_name, group = animal_name, color = animal_name)) +
  theme_bw() +
  geom_borderline(linewidth = 0.8,
                  bordercolour = "black",
                  borderwidth = 0.3,
                  lineend = "round") +
  scale_x_date(limits = c(ymd("2020-01-01"), ymd("2020-12-31")),
               breaks = c(ymd("2020-01-01"),ymd("2020-02-01"),ymd("2020-03-01"),ymd("2020-04-01"),ymd("2020-05-01"),ymd("2020-06-01"),ymd("2020-07-01"),ymd("2020-08-01"),ymd("2020-09-01"), ymd("2020-10-01"), ymd("2020-11-01"), ymd("2020-12-01"), ymd("2021-1-01")),
               labels = c('J','F','M','A','M','J','J','A','S','O','N','D', 'J')) +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "none") +
  scale_color_manual(values = c("#F0A0FF", "#0075DC", "#993F00","#4A6990FF", "#4C005C", "#C20088", "#005C31", "#2BCE48", "#FFCC99", "#808080","#94FFB5", "#8F7C00", "#9DCC00")) +
  ggtitle("Foray loop")
```

Summer plots
```{r}
# Data summaries
summer_movements <- amwo_data_reconstructed %>% 
  filter(primary_step_state == "Migratory (summer)" | prior_step == "Migratory (summer)") %>% 
  mutate(date_standardized = ymd(paste0("2020-", month(time), "-", day(time))))

summer_summary <- summer_movements %>% 
  group_by(animal_name) %>% 
  summarise(min_date = min(date_standardized), max_date = max(date_standardized)) %>% 
  pivot_longer(cols = c(min_date, max_date), 
               names_to = "summary_type")

summer_sorted <- summer_summary %>% 
  filter(summary_type == "min_date") %>% 
  arrange(desc(value)) %>% 
  pull(animal_name)

summer_summary <- summer_summary %>% 
  mutate(animal_name = factor(animal_name, levels = summer_sorted))

summer_sf <- summer_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise()

summer_line <- summer_movements %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4326) %>%
  st_transform(5070) %>% 
  group_by(animal_name) %>%
  summarise() %>% 
  st_cast("LINESTRING")

# Revised map
summer_map <- template_map +
  geom_sf(data = summer_line, linewidth = 0.5, colour = c("#F0A0FF", "#0075DC", "#993F00")) + 
  geom_sf(data = summer_sf, size = 1, color = "black") +
  geom_sf(data = summer_sf, size = 0.8, color = c("#F0A0FF", "#0075DC", "#993F00")) +
  #coord_sf(xlim = c(-100, -60), ylim = c(25, 55), expand = FALSE) +
  coord_sf(xlim = c(-408613, 2763993), ylim = c(226720.6, 3589842), expand = FALSE) +
  theme(legend.position = "bottom",
        legend.margin=margin(t = 10),
        plot.margin = margin(b = 10)) +
  ggtitle("Summer migration")

# Revised timeline
summer_timeline <- ggplot(data = summer_summary, mapping = aes(x = value, y = animal_name, group = animal_name, color = animal_name)) +
  theme_bw() +
  geom_borderline(linewidth = 0.8,
                  bordercolour = "black",
                  borderwidth = 0.3,
                  lineend = "round") +
  scale_x_date(limits = c(ymd("2020-01-01"), ymd("2020-12-31")),
               breaks = c(ymd("2020-01-01"),ymd("2020-02-01"),ymd("2020-03-01"),ymd("2020-04-01"),ymd("2020-05-01"),ymd("2020-06-01"),ymd("2020-07-01"),ymd("2020-08-01"),ymd("2020-09-01"), ymd("2020-10-01"), ymd("2020-11-01"), ymd("2020-12-01"), ymd("2021-1-01")),
               labels = c('J','F','M','A','M','J','J','A','S','O','N','D', 'J')) +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.position = "none") +
  scale_color_manual(values = c("#F0A0FF", "#0075DC", "#993F00")) +
  ggtitle("Summer migration")
```

Showing how these can all be rendered in a single plot
```{r}
# legend_desc <- get_legend(template_map)

timelines_combined <- ggarrange(summer_timeline, dispersal_timeline, foray_timeline, nrow = 3, ncol = 1, heights = c(3+5, 3+5, 13+5))

plots_arranged <- ggarrange(summer_map, dispersal_map, foray_map, timelines_combined, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom") #legend.grob = legend_desc,

ggsave(filename = here::here("auxiliary_state_plot", "auxiliary_state_plot_5_5_2023.png"), plot = plots_arranged, dpi = 300, bg = "white", height = 7.5, width = 7)
```

