---
title: "R Notebook"
output: html_notebook
---
```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(here)
```

```{r include=FALSE}
amwo_data_reconstructed <- readRDS(here("classifier_integrated", "fac_primary_state_delineation.rds")) %>% 
  mutate(standardized_date = mdy(paste0(month(time), "/", day(time), "/2020")))

capture_dates <- readxl::read_excel(here("capture_sheet.xlsx"), col_types = c("text", "text", "date", "numeric", "numeric", "numeric", "numeric", "text", "text", "text", "text", "text", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text", "text", "text", "text", "text", "text")) %>%
  mutate(`Argos_ID` = as.character(`Argos_ID`)) %>%
  transmute(animal_name = `Movebank_ID`,
            sex = Sex) %>% 
  filter(animal_name != "NA")

amwo_data_reconstructed <- amwo_data_reconstructed %>% 
  left_join(capture_dates)
```

Reclassify based on nesting attempts (use only for graphing) and remove classes that I don't want to graph
```{r}
amwo_data_reconstructed_male <- amwo_data_reconstructed %>% 
  filter(!(primary_step_state %in% c("Unknown- bugged frequent schedule", "Dispersal", "Foray loop", "Migratory (summer)")),
         sex == "Male")

amwo_data_reconstructed_female <- amwo_data_reconstructed %>% 
  filter(!(primary_step_state %in% c("Unknown- bugged frequent schedule", "Dispersal", "Foray loop", "Migratory (summer)")),
         sex == "Female")
```

Calculate % of points in any given week that belong to each step
```{r}
weekly_pt1_male <- amwo_data_reconstructed_male %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week) %>% 
  summarise(standardized_date = mean(standardized_date), total = n()) %>% #mean
  ungroup()

weekly_pt2_male <- amwo_data_reconstructed_male %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week, primary_step_state) %>% 
  tally() %>% 
  ungroup() %>% 
  left_join(weekly_pt1_male) %>% 
  mutate(pct = n/total)

weekly_pt1_female <- amwo_data_reconstructed_female %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week) %>% 
  summarise(standardized_date = mean(standardized_date), total = n()) %>% #mean
  ungroup()

weekly_pt2_female <- amwo_data_reconstructed_female %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week, primary_step_state) %>% 
  tally() %>% 
  ungroup() %>% 
  left_join(weekly_pt1_female) %>% 
  mutate(pct = n/total)

days_of_month <- seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by = 1) %>% 
  ceiling_date(., "weeks") %>% 
  unique(.) - 4

tibble(week = 1:53, week_end = days_of_month)

weekly_pt2_male <- weekly_pt2_male %>% 
  left_join(tibble(week = 1:53, week_end = days_of_month)) %>% 
  mutate(standardized_date = week_end,
         week_end = NULL,
         sex = "Male")

weekly_pt2_female <- weekly_pt2_female %>% 
  left_join(tibble(week = 1:53, week_end = days_of_month)) %>% 
  mutate(standardized_date = week_end,
         week_end = NULL,
         sex = "Female")

weekly_pt2 <- weekly_pt2_male %>% 
  bind_rows(weekly_pt2_female)

weekly_pt2$primary_step_state <- factor(weekly_pt2$primary_step_state, levels = c("Stationary", "Migratory (fall)", "Migratory (spring)"), ordered = TRUE)
```

Get the first and last day of each week
```{r}
week_boundaries <- tibble(date = seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by = 1)) %>% 
  mutate(week = week(date), start = floor_date(date, unit = "weeks", week_start = getOption("lubridate.week.start", 3)), 
         end = ceiling_date(date, unit = "weeks", week_start = getOption("lubridate.week.start", 3))) %>% 
  mutate(date = NULL) %>% 
  distinct()

weekly_pt2 <- weekly_pt2 %>% 
  left_join(week_boundaries)
```


```{r}
weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (fall)", sex == "Male") %>% 
  arrange(desc(pct)) %>% 
  head(n = 1)

weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (fall)", sex == "Female") %>% 
  arrange(desc(pct)) %>% 
  head(n = 1)

weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (spring)", sex == "Male") %>% 
  arrange(desc(pct)) %>% 
  head(n = 1)

weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (spring)", sex == "Female") %>% 
  arrange(desc(pct)) %>% 
  head(n = 1)
```

