---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(here)
```

```{r include=FALSE}
amwo_data_reconstructed <- readRDS(here::here("classifier_integrated", "fac_primary_state_delineation.rds")) %>% 
  mutate(standardized_date = mdy(paste0(month(time), "/", day(time), "/2020")))

capture_dates <- readxl::read_excel(here("capture_sheet.xlsx"), col_types = c("text", "text", "date", "numeric", "numeric", "numeric", "numeric", "text", "text", "text", "text", "text", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "text", "text", "text", "text", "text", "text")) %>%
  mutate(`Argos_ID` = as.character(`Argos_ID`)) %>%
  transmute(animal_name = `Movebank_ID`,
            sex = Sex) %>% 
  filter(animal_name != "NA")

amwo_data_reconstructed <- amwo_data_reconstructed %>% 
  left_join(capture_dates)
```

Reclassify based on nesting attempts (use only for graphing) and remove classes that I don't want to graph
```{r}
amwo_data_reconstructed_male <- amwo_data_reconstructed %>% 
  filter(!(primary_step_state %in% c("Unknown- bugged frequent schedule", "Dispersal", "Foray loop", "Migratory (summer)")),
         sex == "Male")

amwo_data_reconstructed_female <- amwo_data_reconstructed %>% 
  filter(!(primary_step_state %in% c("Unknown- bugged frequent schedule", "Dispersal", "Foray loop", "Migratory (summer)")),
         sex == "Female")
```

Calculate % of points in any given week that belong to each step
```{r}
weekly_pt1_male <- amwo_data_reconstructed_male %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week) %>% 
  summarise(standardized_date = mean(standardized_date), total = n()) %>% #mean
  ungroup()

weekly_pt2_male <- amwo_data_reconstructed_male %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week, primary_step_state) %>% 
  tally() %>% 
  ungroup() %>% 
  left_join(weekly_pt1_male) %>% 
  mutate(pct = n/total)

weekly_pt1_female <- amwo_data_reconstructed_female %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week) %>% 
  summarise(standardized_date = mean(standardized_date), total = n()) %>% #mean
  ungroup()

weekly_pt2_female <- amwo_data_reconstructed_female %>% 
  mutate(week = week(standardized_date)) %>% 
  group_by(week, primary_step_state) %>% 
  tally() %>% 
  ungroup() %>% 
  left_join(weekly_pt1_female) %>% 
  mutate(pct = n/total)

days_of_month <- seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by = 1) %>% 
  ceiling_date(., "weeks") %>% 
  unique(.) - 4

tibble(week = 1:53, week_end = days_of_month)

weekly_pt2_male <- weekly_pt2_male %>% 
  left_join(tibble(week = 1:53, week_end = days_of_month)) %>% 
  mutate(standardized_date = week_end,
         week_end = NULL,
         sex = "Male")

weekly_pt2_female <- weekly_pt2_female %>% 
  left_join(tibble(week = 1:53, week_end = days_of_month)) %>% 
  mutate(standardized_date = week_end,
         week_end = NULL,
         sex = "Female")

weekly_pt2 <- weekly_pt2_male %>% 
  bind_rows(weekly_pt2_female)

weekly_pt2$primary_step_state <- factor(weekly_pt2$primary_step_state, levels = c("Stationary", "Migratory (fall)", "Migratory (spring)"), ordered = TRUE)
```


```{r}
mig_plot_fall <- weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (fall)") %>% 
  mutate(standardized_date = if_else(month(standardized_date) %in% c(1:7), mdy(paste0(month(standardized_date), "/", day(standardized_date), "/2021")), standardized_date)) %>% 
  filter(!(week %in% c(1, 53))) %>% # 1 replace the 53rd week with a week starting on Jan 1 with an averaged value 
  bind_rows(tibble(week = 1, primary_step_state = "Migratory (fall)", n = 25 + 10, standardized_date = ymd("2020-12-31"), total = 263 + 111, pct = (25 + 10)/(263 + 111),
            sex = "Male")) %>% 
  bind_rows(tibble(week = 1, primary_step_state = "Migratory (fall)", n = 28 + 19, standardized_date = ymd("2020-12-31"), total = 270 + 138, pct = (28 + 19)/(270 + 138),
            sex = "Female")) %>% 
  mutate(sex = factor(sex, levels = c("Male", "Female"), ordered = TRUE)) %>% 
  ggplot(data = ., mapping = aes(x = standardized_date, y = pct)) +
  geom_col(fill = "#FA6900FF", col = "black") +
  theme_bw() + 
  scale_x_date(name = NULL,
               date_labels = "%b %d",
               breaks = ymd(c("2021-01-1", "2021-02-1", "2021-03-1", "2021-04-1", "2021-05-1", "2021-06-1", "2021-07-1", "2020-08-1", "2020-09-1", "2020-10-1", "2020-11-1", "2020-12-1")),
               minor_breaks = ymd(c("2021-01-15", "2021-02-15", "2021-03-15", "2021-04-15", "2021-05-15", "2021-06-15", "2020-07-15", "2020-08-15", "2020-09-15", "2020-10-15", "2020-11-15", "2020-12-15")),
               limits = c(ymd("2020-10-1"), ymd("2021-3-1"))) +
  scale_y_continuous(name = NULL,
                     labels = scales::percent,
                     breaks = seq(from = 0, to = 1, by = 0.2),
                     minor_breaks = seq(from = 0.1, to = 0.9, by = 0.2),
                     limits = c(0, 1)) +
  ggtitle("Fall") +
  facet_wrap(vars(sex), nrow = 2) + 
  guides(fill="none") +
  theme(plot.title = element_text(hjust = 0.5),
        strip.background = element_blank(), 
        strip.text = element_blank())

mig_plot_fall
```


```{r}
mig_plot_spring <- weekly_pt2 %>% 
  filter(primary_step_state == "Migratory (spring)") %>%
  mutate(sex = factor(sex, levels = c("Male", "Female"), ordered = TRUE)) %>% 
  ggplot(data = ., mapping = aes(x = standardized_date, y = pct)) + 
  geom_col(fill = "#69D2E7FF", col = "black") +
  theme_bw() + 
  scale_x_date(name = NULL,
               date_labels = "%b %d",
               breaks = ymd(c("2020-01-1", "2020-02-1", "2020-03-1", "2020-04-1", "2020-05-1", "2020-06-1", "2020-07-1", "2020-08-1", "2020-09-1", "2020-10-1", "2020-11-1", "2020-12-1")),
               minor_breaks = ymd(c("2020-01-15", "2020-02-15", "2020-03-15", "2020-04-15", "2020-05-15", "2020-06-15", "2020-07-15", "2020-08-15", "2020-09-15", "2020-10-15", "2020-11-15", "2020-12-15")),
               limits = ymd(c("2020-01-1", "2020-07-01"))) +
  scale_y_continuous(name = NULL,
                     labels = scales::percent,
                     breaks = seq(from = 0, to = 1, by = 0.2),
                     minor_breaks = seq(from = 0.1, to = 0.9, by = 0.2),
                     limits = c(0, 1)) +
  #theme(panel.grid.minor = element_blank()) +
  ggtitle("Spring") +
  facet_wrap(vars(sex), nrow = 2, strip.position = "right") + 
  guides(fill="none") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

mig_plot_spring
```

```{r}
ggarrange(mig_plot_fall, mig_plot_spring, 
          ncol = 2, 
          nrow = 1) %>% 
  annotate_figure(bottom = "Date", left = "Percent migratory") +
  bgcolor("#FFFFFF")

ggsave(filename = "migratory_state_histograms_6_2_23.png", width = 10.5/1.5, height = 6/1.5)
```
